services:
  - type: web
    name: resume-building-project
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resume_project.wsgi:application

envVars:
  - key: PYTHON_VERSION
    value: 3.11.9