# Generated by Django 6.0.4 on 2026-04-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin', models.URLField()),
                ('github', models.URLField()),
                ('career_objective', models.TextField()),
                ('education', models.TextField()),
                ('technical_skills', models.TextField()),
                ('projects', models.TextField()),
                ('certifications', models.TextField()),
                ('soft_skills', models.TextField()),
            ],
        ),
    ]
